# 서버포트
server:
  port: 8080

spring:
# h2 설정
  h2:
    console:
      enabled: true
      path: /h2-console

  # 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # redis 설정
  data:
    redis:
      host: localhost
      port: 6379

  # mail
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #Oauth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            client-name: Google
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile

          kakao:
            client-id:
            client-secret:
            client-name: Kakao
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
                - account_email
                - profile_nickname
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret:
    key:
  access-token-expire-time: 10800000 # 3시간
  refresh-token-expire-time: 86400000 # 1일