# 서버포트
server:
  port: 8080

spring:
# h2 설정
  h2:
    console:
      enabled: true
      path: /h2-console

  # 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # redis 설정
  data:
    redis:
      host: localhost
      port: 6379

  # mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: qkrwldn0818@gmail.com
    password: zkoxlojfsbemspgc
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret:
    key: 64K07ZSE66Gc7KCd7Yq464qU66ek7Jqw67OE66Gc64uk6re465+s64uI6re464Ol64SI7J2Y64+I7J2E7JWE6ru07I2o65287KCc67Cc
  access-token-expire-time: 10800000 # 3시간
  refresh-token-expire-time: 86400000 # 1일